<a href="https://colab.research.google.com/github/fbghkh1999/Multi_predict_model_base-on-different-datasets/blob/main/multiple%20_linear_regression/Multiple_linear_regression_boston_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
% matplotlib inline

In [ ]:
from sklearn.datasets import load_boston
boston=load_boston()
x=boston.data
y=boston.target


In [ ]:
from sklearn.model_selection import  train_test_split
X_train, X_test, y_train, y_test=train_test_split( x,y, random_state=76,test_size=0.3,train_size=0.7)
X_train

array([[3.83518e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 3.05900e+01],
       [1.52880e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.63020e+02, 2.32400e+01],
       [7.84200e-01, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.86750e+02, 1.46700e+01],
       ...,
       [5.29305e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.78380e+02, 1.87600e+01],
       [6.07600e-02, 0.00000e+00, 1.19300e+01, ..., 2.10000e+01,
        3.96900e+02, 5.64000e+00],
       [1.46336e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        3.74430e+02, 1.73000e+00]])

In [ ]:
# normalize dataset
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler(feature_range=(0,1))
x_train=scale.fit_transform(X_train)
x_test=scale.fit_transform(X_test)
y_train=y_train.reshape(-1,1)
y_train=scale.fit_transform(y_train)



In [ ]:
from sklearn.linear_model import LinearRegression
linearReg=LinearRegression()
linearReg.fit(x_train,y_train)
y_pred=linearReg.predict(x_test)
y_pred_new=scale.inverse_transform(y_pred)


In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
mean_absolute_error(y_test,y_pred_new)
y_pred_new

array([[11.57857042],
       [18.02830278],
       [23.45891598],
       [31.3677831 ],
       [29.47967977],
       [26.56906426],
       [20.86428828],
       [24.49444748],
       [27.66713069],
       [17.39590357],
       [18.86176708],
       [14.33713049],
       [11.90786487],
       [23.10773711],
       [17.92063489],
       [23.35557296],
       [18.48187283],
       [ 4.88817524],
       [20.55573236],
       [19.03954416],
       [21.77215964],
       [29.81600454],
       [20.65749596],
       [18.74890092],
       [10.22444955],
       [29.26815029],
       [26.3728474 ],
       [34.2628906 ],
       [20.1339041 ],
       [23.8480181 ],
       [18.10057513],
       [18.80171534],
       [23.00799611],
       [22.63077944],
       [28.39172842],
       [22.62851069],
       [21.59171569],
       [19.75822865],
       [23.04134683],
       [20.31014301],
       [12.56593393],
       [19.74757558],
       [37.7544007 ],
       [24.66674902],
       [19.41411963],
       [22

In [ ]:
y_pred

array([[ 0.51969849],
       [ 0.2822739 ],
       [ 0.34466602],
       [-0.08933833],
       [ 0.19486078],
       [ 0.31369087],
       [ 0.34159315],
       [ 0.01305545],
       [ 0.44727679],
       [ 0.88526116],
       [ 0.72781221],
       [ 0.12500613],
       [ 0.69003118],
       [ 0.40082563],
       [ 0.31098206],
       [ 0.16829605],
       [ 0.55977435],
       [ 0.41067964],
       [ 0.15020573],
       [ 0.24863068],
       [ 0.16486943],
       [ 0.52149582],
       [ 0.49072799],
       [ 0.1621135 ],
       [ 0.19713965],
       [ 0.27305541],
       [ 0.18945348],
       [ 0.28146044],
       [ 0.784591  ],
       [ 0.26159859],
       [-0.16704539],
       [ 0.11895035],
       [ 0.25785974],
       [ 0.60350093],
       [ 0.15865545],
       [ 0.056394  ],
       [ 0.40433962],
       [ 0.26160912],
       [ 0.22410111],
       [ 0.29643147],
       [ 0.171291  ],
       [ 0.44284606],
       [ 0.43833995],
       [ 0.84506503],
       [ 0.20920643],
       [ 0

In [ ]:
mean_squared_error(y_test,y_pred_new)

18.694472333807862

In [ ]:
r2_score(y_test,y_pred_new)

0.714586367888878

In [ ]:
#polynomial_linear_regression


In [44]:
from sklearn.datasets import load_boston
boston=load_boston()
x1=boston.data[:,5]
y1=boston.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(x1,y1,random_state=76,test_size=0.3,train_size=0.7)

In [49]:
from sklearn.preprocessing import  PolynomialFeatures
poly=PolynomialFeatures(degree=2)
X_train=X_train.reshape(-1,1)
Poly_x_train=poly.fit_transform(X_train)
X_test=X_test.reshape(-1,1)
poly_x_test=poly.fit_transform(X_test)

In [51]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(Poly_x_train,y_train)
poly_y=lr.predict(poly_x_test)

In [53]:
poly_y
r2_score(y_test,poly_y)
# for this dataset is not good

0.6581796714410476